name: test_online_store
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: inter
      fonts:
        - asset: fonts/inter/Inter-Medium.ttf
    - family: montserrat
      fonts:
        - asset: fonts/montserrat/Montserrat-Medium.ttf
        - asset: fonts/montserrat/Montserrat-SemiBold.ttf
    - family: raleway
      fonts:
        - asset: fonts/raleway/Raleway-Bold.ttf
        - asset: fonts/raleway/Raleway-Medium.ttf
        - asset: fonts/raleway/Raleway-SemiBold.ttf
    - family: vela-sans
      fonts:
        - asset: fonts/velaSans/VelaSans-Bold.ttf
        - asset: fonts/velaSans/VelaSans-Regular.ttf

  assets:
    - assets/icons/House.png
    - assets/icons/MagnifyingGlass.png
    - assets/icons/ShoppingCartSimple.png
    - assets/icons/User.png
    - assets/pictures/body.png
    - assets/pictures/cream_blue.png
    - assets/pictures/cream_pink.png
    - assets/pictures/face.png
    - assets/pictures/headLogo.png
    - assets/pictures/promotion.png
    - assets/pictures/background/background.png
    - assets/pictures/cream_green/creamGreen1.png
    - assets/pictures/cream_green/creamGreen2.png
    - assets/pictures/cream_pink/creamPink1.png
    - assets/pictures/cream_pink/creamPink2.png
    - assets/pictures/cream_red/creamRed1.png
    - assets/pictures/cream_red/creamRed2.png
    - assets/pictures/shadow_cream/cleansing.png
    - assets/pictures/shadow_cream/day_cream.png
    - assets/pictures/shadow_cream/demakage.png
    - assets/pictures/shadow_cream/serum.png
